<a href="https://colab.research.google.com/github/tilakbhusan/Umbrella/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, (3, 3))

# Step 2: Interchange rows and columns (transpose the array)
transposed_array = array.T

print("Original Array:")
print(array)
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[54 28 53]
 [15 42 23]
 [55 43 20]]

Transposed Array:
[[54 15 55]
 [28 42 43]
 [53 23 20]]


Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [4]:
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)  # Array with values from 1 to 10

# Step 2: Reshape the array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape the array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [5]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Step 2: Add a border of zeros around the array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 Array:")
print(array_4x4)
print("\n6x6 Array with Border of Zeros:")
print(array_6x6)


4x4 Array:
[[0.1070322  0.26218912 0.3961933  0.94577381]
 [0.40133282 0.47463133 0.83981553 0.24457653]
 [0.58924538 0.96079105 0.99876684 0.94165217]
 [0.16638278 0.34515313 0.37932104 0.62788738]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.1070322  0.26218912 0.3961933  0.94577381 0.        ]
 [0.         0.40133282 0.47463133 0.83981553 0.24457653 0.        ]
 [0.         0.58924538 0.96079105 0.99876684 0.94165217 0.        ]
 [0.         0.16638278 0.34515313 0.37932104 0.62788738 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [6]:
# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [7]:
# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply uppercase transformation
uppercase_array = np.char.upper(string_array)

# Apply lowercase transformation
lowercase_array = np.char.lower(string_array)

# Apply title case transformation
titlecase_array = np.char.title(string_array)

# Apply capitalized transformation (first letter capitalized)
capitalize_array = np.char.capitalize(string_array)

print("Original Array:")
print(string_array)
print("\nUppercase:")
print(uppercase_array)
print("\nLowercase:")
print(lowercase_array)
print("\nTitle Case:")
print(titlecase_array)
print("\nCapitalized:")
print(capitalize_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [8]:
# Create a NumPy array of words
words_array = np.array(['tilak', 'bhusan', 'nayak'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

print("Original Array:")
print(words_array)
print("\nArray with spaces between characters:")
print(spaced_words_array)


Original Array:
['tilak' 'bhusan' 'nayak']

Array with spaces between characters:
['t i l a k' 'b h u s a n' 'n a y a k']


Q7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [9]:
# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform element-wise addition
addition_result = array1 + array2

# Perform element-wise subtraction
subtraction_result = array1 - array2

# Perform element-wise multiplication
multiplication_result = array1 * array2

# Perform element-wise division
# Ensure no division by zero occurs
division_result = np.divide(array1, array2)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition_result)
print("\nElement-wise Subtraction:")
print(subtraction_result)
print("\nElement-wise Multiplication:")
print(multiplication_result)
print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [10]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [11]:
# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, 100)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

print("Random Array:")
print(random_array)
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Array:
[957 417 824 753 181 150 391 129 444 176   3  31 328 929 125 371   5 171
  61 149 473 587 759 581 494 237 615   4 630 734 739 918 789 267 493 823
 585 107 510 619 777 423 928 513 370 337 216  73 855 246  84 203 237 326
 534 441 258 227 519 124 892 418 330  26 531 214 269 703 970 108 727 583
  27 148 103 544 467 696 707 485 331 375 906 179 973 696 466  35 365  26
 164 658 153 962  46 787 459 469 737 400]

Prime Numbers in the Array:
[181, 3, 31, 929, 5, 61, 149, 587, 739, 823, 107, 619, 337, 73, 227, 269, 727, 103, 467, 331, 179, 787]


Q10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [24]:
# Create a NumPy array with daily temperatures for a month
daily_temperatures = np.array([25, 26, 27, 28, 29, 30, 31, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6])
# Calculate the weekly averages
weekly_averages = [daily_temperatures[i:i+7].mean() for i in range(0, len(daily_temperatures), 7)]

print("Weekly Averages:")
for i, average in enumerate(weekly_averages):
    print(f"Week {i+1}: {average}")

Weekly Averages:
Week 1: 28.0
Week 2: 25.0
Week 3: 18.0
Week 4: 11.0
Week 5: 6.5
